import { createApi } from "@reduxjs/toolkit/query/react";
import { baseQueryWithReauth } from "./baseQuery";

export interface Coupon {
  id: string;
  code: string;
  name: string;
  description?: string;
  type:
    | "PERCENTAGE"
    | "FIXED_AMOUNT"
    | "FREE_SHIPPING"
    | "FREE_PRODUCT"
    | "PRODUCT_DISCOUNT";
  status: "ACTIVE" | "INACTIVE" | "EXPIRED" | "DEPLETED";
  discountValue?: number;
  maxDiscountAmount?: number;
  freeProductId?: string;
  freeProductQty?: number;
  freeProduct?: { id: string; name: string; images: string[] };
  applicableProductIds: string[];
  applicableCategoryIds: string[];
  minOrderAmount?: number;
  maxUsageCount?: number;
  usageCount: number;
  perCustomerLimit?: number;
  customerIds: string[];
  startsAt?: string;
  expiresAt?: string;
  isAutoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface CouponsResponse {
  coupons: Coupon[];
  total: number;
  page: number;
  limit: number;
  stats: {
    active: number;
    inactive: number;
    expired: number;
    depleted: number;
    totalUsages: number;
    totalDiscount: number;
  };
}

export interface CouponValidation {
  valid: boolean;
  discount: number;
  freeProduct?: { id: string; name: string; qty: number };
  message?: string;
  couponId?: string;
}

export const couponsApi = createApi({
  reducerPath: "couponsApi",
  baseQuery: baseQueryWithReauth,
  tagTypes: ["Coupons"],
  endpoints: (builder) => ({
    getCoupons: builder.query<
      CouponsResponse,
      { status?: string; page?: number }
    >({
      query: ({ status, page = 1 }) => {
        const params = new URLSearchParams();
        if (status && status !== "all") params.append("status", status);
        params.append("page", String(page));
        return `/merchant/coupons?${params}`;
      },
      providesTags: ["Coupons"],
    }),

    getCouponById: builder.query<Coupon, string>({
      query: (id) => `/merchant/coupons/${id}`,
      providesTags: (result, error, id) => [{ type: "Coupons", id }],
    }),

    createCoupon: builder.mutation<Coupon, Partial<Coupon>>({
      query: (body) => ({
        url: "/merchant/coupons",
        method: "POST",
        body,
      }),
      invalidatesTags: ["Coupons"],
    }),

    updateCoupon: builder.mutation<
      Coupon,
      { id: string; data: Partial<Coupon> }
    >({
      query: ({ id, data }) => ({
        url: `/merchant/coupons/${id}`,
        method: "PATCH",
        body: data,
      }),
      invalidatesTags: ["Coupons"],
    }),

    toggleCouponStatus: builder.mutation<Coupon, string>({
      query: (id) => ({
        url: `/merchant/coupons/${id}/toggle`,
        method: "PATCH",
      }),
      invalidatesTags: ["Coupons"],
    }),

    deleteCoupon: builder.mutation<void, string>({
      query: (id) => ({
        url: `/merchant/coupons/${id}`,
        method: "DELETE",
      }),
      invalidatesTags: ["Coupons"],
    }),

    generateCode: builder.mutation<{ code: string }, { prefix?: string }>({
      query: (body) => ({
        url: "/merchant/coupons/generate-code",
        method: "POST",
        body,
      }),
    }),

    validateCoupon: builder.mutation<
      CouponValidation,
      {
        code: string;
        storeId?: string;
        storeSlug?: string;
        orderTotal: number;
        customerId?: string;
        productIds?: string[];
      }
    >({
      query: (body) => ({
        url: "/coupons/validate",
        method: "POST",
        body,
      }),
    }),
  }),
});

export const {
  useGetCouponsQuery,
  useGetCouponByIdQuery,
  useCreateCouponMutation,
  useUpdateCouponMutation,
  useToggleCouponStatusMutation,
  useDeleteCouponMutation,
  useGenerateCodeMutation,
  useValidateCouponMutation,
} = couponsApi;
