export { normalizeAIOutput, type NormalizationResult, type NormalizationError } from "./normalization";
export {
  LandingPageContentSchema,
  LandingSectionSchema,
  CANONICAL_SECTION_ORDER,
  type LandingPageContent,
  type LandingSection,
  type SectionType,
  // Individual section schemas
  HeroSectionSchema,
  ProblemSectionSchema,
  SolutionSectionSchema,
  FeaturesSectionSchema,
  BenefitsSectionSchema,
  GallerySectionSchema,
  UseCasesSectionSchema,
  ComparisonSectionSchema,
  TrustSectionSchema,
  TestimonialsSectionSchema,
  OfferSectionSchema,
  FaqSectionSchema,
  FinalCtaSectionSchema,
  // Individual section types
  type HeroSection,
  type ProblemSection,
  type SolutionSection,
  type FeaturesSection,
  type BenefitsSection,
  type GallerySection,
  type UseCasesSection,
  type ComparisonSection,
  type TrustSection,
  type TestimonialsSection,
  type OfferSection,
  type FaqSection,
  type FinalCtaSection,
} from "./schemas";
